DataRetrieval/DataRetrieval/Models/ErrorViewModel.cs
namespace DataRetrieval.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DataRetrieval/DataRetrieval/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DataRetrieval.Controllers
{
    public class DataController : Controller
    {
        private readonly ApplicationDbContext context;

        public DataController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Не говнокод, а скоростное программирование (хотя, учитывая, что даже проверки на дубликаты нет...)
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> ImportCsv(IFormFile file)
        {
            try
            {
                var rawData = await ReadAsListAsync(file);

                rawData.RemoveAt(0);

                var movies = new List<Movie>();
                foreach (var line in rawData)
                {
                    try
                    {
                        var arr = line.Split(",");
                        var str = arr[1].Trim();
                        movies.Add(new Movie
                        {
                            id = Convert.ToInt32(arr[0].TrimStart('0')),
                            name = str.Substring(0, (str.Length - 6)).Trim(),
                            year = Convert.ToInt32(str.Substring(str.Length - 5, 4))
                        });
                    }
                    catch (Exception)
                    {
                        // потеряем пару битых строк - пофиг
                    }

                }

                await context.AddRangeAsync(movies);
                await context.SaveChangesAsync();
                return Json(movies.Count);
            }
            catch (Exception e)
            {
                return Json(new { e.Message, e.StackTrace });
            }
        }

        public static async Task<List<string>> ReadAsListAsync(IFormFile file)
        {
            var result = new List<string>();
            using (var reader = new StreamReader(file.OpenReadStream()))
            {
                while (reader.Peek() >= 0)
                    result.Add(await reader.ReadLineAsync());
            }
            return result;
        }
    }
}

DataRetrieval/DataRetrieval/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using DataRetrieval.DbProvider;
using Microsoft.AspNetCore.Mvc;
using DataRetrieval.Models;
using Lucene.Net.Index;
using Lucene.Net.Search;
using Lucene.Net.Documents;

namespace DataRetrieval.Controllers
{
    public class HomeController : Controller
    {
        private readonly PostgreSqlDbProvider dbProvider;

        private readonly LucyAdapter lucyAdapter;

        public HomeController(PostgreSqlDbProvider dbProvider, LucyAdapter lucyAdapter)
        {
            this.dbProvider = dbProvider;
            this.lucyAdapter = lucyAdapter;
            lucyAdapter.InitLucy();
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public IActionResult Lab1()
        {
            return View();
        }

        public async Task<IActionResult> TestGetAllRowsFromMovies()
        {
            var x = await dbProvider.GetRowsAsync("movies");

            return Json(x);
        }

        public async Task<IActionResult> Search(string query)
        {
            try
            {
                var pattern = @".+\((\d{4})\)";
                var yearFinder = new Regex(pattern);
                var match = yearFinder.Match(query);
                var year = 0;

                query = query.Replace("%", @"\%").Replace("_", @"\_");

                if (match.Success)
                {
                    int.TryParse(match.Groups[1].Value, out year);

                    query = Regex.Replace(query, @"\((\d{4})\)", "");
                }

                var yearCondition = year == 0 ? "" : $"OR year = {year}";
                var result =
                    await dbProvider.GetRowsAsync(condition: $"name ~~* '%{query}%' {yearCondition}", count: 10);

                return Json(result);
            }
            catch (System.Exception e)
            {
                return Json(new {e.Message, e.StackTrace});
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }

        /// <summary>
        /// On base of https://lucenenet.apache.org
        /// </summary>
        /// <param name="query"></param>
        /// <returns></returns>
        public IEnumerable<(string name, int year)> SearchWithLucy(string query)
        {
            var words = query.Split(' ').ToList();
            var searcher = new IndexSearcher(lucyAdapter.lucyWriter.GetReader(applyAllDeletes: true));

            var totalResults = new List<Document>();
            //word
            MultiPhraseQuery multiPhraseQuery;
            foreach (var word in words)
            {
                multiPhraseQuery = new MultiPhraseQuery();
                if (string.IsNullOrEmpty(word)) continue;
                multiPhraseQuery.Add(new Term("name_word", word));
                var docs = searcher.Search(multiPhraseQuery, 10).ScoreDocs;
                foreach (var doc in docs)
                {
                    var document = searcher.Doc(doc.Doc);
                    if (totalResults.All(f => f.GetField("id").GetInt32Value() != document.GetField("id").GetInt32Value()))
                        totalResults.Add(document);
                }
            }

            // full name
            multiPhraseQuery = new MultiPhraseQuery();
            multiPhraseQuery.Add(new Term("full_name", query));
            var scoreDocs = searcher.Search(multiPhraseQuery, 10).ScoreDocs;
            foreach (var scoreDoc in scoreDocs)
            {
                var doc = searcher.Doc(scoreDoc.Doc);
                if (totalResults.All(f => f.GetField("id").GetInt32Value() != doc.GetField("id").GetInt32Value()))
                    totalResults.Add(doc);
            }

            //word parts
            foreach (var word in words)
            {
                if (string.IsNullOrEmpty(word)) continue;
                var wildcardQuery = new WildcardQuery(new Term("name_word", "*" + word + "*"));
                var docs = searcher.Search(wildcardQuery, 10).ScoreDocs;
                foreach (var doc in docs)
                {
                    var document = searcher.Doc(doc.Doc);
                    if (totalResults.All(f => f.GetField("id").GetInt32Value() != document.GetField("id").GetInt32Value()))
                        totalResults.Add(document);
                }
            }

            //year and word part
            var number = 0;
            foreach (var word in words)
            {
                var result = int.TryParse(word, out number);
                if (!result) continue;
                words.RemoveAt(words.IndexOf(word));
                break;
            }

            if (number != 0)
            {
                foreach (var word in words)
                {
                    if (string.IsNullOrEmpty(word)) continue;
                    var booleanQuery = new BooleanQuery();

                    var wildcardQuery = new WildcardQuery(new Term("name_word", "*" + word + "*"));
                    var rangeQuery = NumericRangeQuery.NewInt32Range("year", 1, number, number, true, true);

                    booleanQuery.Add(wildcardQuery, Occur.SHOULD);
                    booleanQuery.Add(rangeQuery, Occur.SHOULD);
                    var docs = searcher.Search(booleanQuery, 10).ScoreDocs;
                    foreach (var doc in docs)
                    {
                        var foundDoc = searcher.Doc(doc.Doc);
                        if (totalResults.All(f => f.GetField("id").GetInt32Value() != foundDoc.GetField("id").GetInt32Value()))
                            totalResults.Add(foundDoc);
                    }
                }
            }

            foreach (var doc in totalResults.Take(10))
            {
                yield return (doc.GetValues("full_name")[0], (int) doc.GetField("year").GetInt32Value());
            }
        }
    }
}

DataRetrieval/DataRetrieval/Views/Data/Index.cshtml
@{
    ViewData["Title"] = "Data Page";
}

<div class="text-center">
    <form method="post" enctype="multipart/form-data" asp-controller="Data" asp-action="ImportCSV">
        <div class="form-group">
            <div class="col-md-10">
                <p>Upload csv:</p>
                <input type="file" name="file"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Upload"/>
            </div>
        </div>
    </form>
</div>

DataRetrieval/DataRetrieval/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    Data Retrieval labs
</div>

DataRetrieval/DataRetrieval/Views/Home/Lab1.cshtml
@{
    ViewData["Title"] = "Lab1";
}

<h1>Labs</h1>
<div class="text-center">
    <input id="query" placeholder="Например test (2009)" />
    <input id="search" type="button" value="Search" />
    <input id="lucy-search" type="button" value="Search with Lucy" />
    <br />
    Результаты запроса
    <br />
    <textarea rows="12" style="width: 750px" id="result"></textarea>
</div>

@section Scripts
{
    <script src="~/jquery/jquery.min.js"></script>
    <script>

        $(function() {
            console.log("ready!");

            const input = $("#search");

            input.click(function() {

                input.prop('disabled', true);
                const query = $("#query").val();

                let resultText = "";

                $.get(`/Home/Search?query=${query}`)
                    .done(function(data) {
                        console.log(data);
                        try {
                            data.forEach(function (element) {
                                resultText += `${element.name} (${element.year})\n`;
                            });

                            $("#result").val(resultText.length > 0 ? resultText : "Nothing found :(");
                        } catch (e) {
                            console.log(e);
                        }

                    })
                    .always(function() {
                        input.prop('disabled', false);
                    });
            });


            const lucy = $("#lucy-search");
            lucy.click(function() {

                lucy.prop('disabled', true);
                const query = $("#query").val();

                let resultText = "";

                $.get(`/Home/SearchWithLucy?query=${query}`)
                    .done(function(data) {
                        console.log(data);
                        try {
                            data.forEach(function (element) {
                                resultText += `${element.item1} (${element.item2})\n`;
                            });

                            $("#result").val(resultText.length > 0 ? resultText : "Nothing found :(");
                        } catch (e) {
                            console.log(e);
                        }

                    })
                    .always(function() {
                        lucy.prop('disabled', false);
                    });
            });


        });
    </script>
}

DataRetrieval/DataRetrieval/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DataRetrieval</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DataRetrieval</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Lab1">Labs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - DataRetrieval
        </div>
    </footer>

    <environment include="Development">
        <script src="~/jquery/jquery.js"></script>
        <script src="~/bootstrap/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/bootstrap/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>